lesson 02 r.1
alx-t/blog-react-base pull request #2
Opened 2016-12-21 20:01 UTC by alx-t

1. че-то не поборол bootstrap. попробовал несколько вариантов - не взлетает. все выводится, классы вроде как правильные, но правильного оформления нет. что сделал не так?

2016-12-23 07:57 UTC, index01d requested changes
весьма необычный подход с подключением create-app, я чуточку позднее еще гляну и скажу почему не затягивается бутстрэп. А пока есть несколько замечаний по существу.

2016-12-23 07:57 UTC, index01d commented on src/components/BlogList.jsx
> +  items: PropTypes.shape({ items: PropTypes.array })
можно затянуть тип из BlogItem.propTypes

2016-12-23 07:57 UTC, index01d commented on src/components/BlogItem.jsx
> +  image: PropTypes.shape({
можно затянуть тип из Image.propTypes

2016-12-23 07:57 UTC, index01d commented on src/components/BlogItem.jsx
> +  author: PropTypes.shape({
плохо, когда ключ author, а внутри не только author. Поэтому и предлагал слово meta

2016-12-23 14:37 UTC, alx-t commented
поправил все кроме затянуть в BlogList тип из BlogItem.propTypes, перепробовал разные варианты.

2016-12-25 10:33 UTC, index01d commented
подсказка: http://jsbin.com/ketevu/edit?js,console,output

2016-12-25 13:03 UTC, alx-t commented
Большое спасибо! этот вариант я тож пробовал, смутила ошибка (ниже), че-то ступил, что искать дальше нужно было ((
![image](https://cloud.githubusercontent.com/assets/11555672/21471173/786ca3ba-cab9-11e6-9715-ad82a666002d.png)

2016-12-26 08:00 UTC, index01d approved these changes

2016-12-26 09:48 UTC, merged